### ISSUE TITLE
Dataset - versioning

### ISSUE THREAD

**Issue by AudreyCLEVY** [etalab-ia/eg1#42]
@dtrckd  what do you think of the idea of having a ‘versioning’ vision of our evaluation dataset? 
Because if we change a question AND/OR, above all, a ground truth, we will no longer be able to replay the experiments accurately and obtain ‘similar’ results.

**Comment by dtrckd** [comment]
Yes you're right, and that is why the datasets are "read only", there is no route to update them because it will break the "num_line" reference.

I think versioning is a difficult task (if we want to be able to update a dataset), and a risky path if we engage in it to soon.

The simpler way to handle this at the moment, is to  encourage the user to version their dataset themselves with a new name (a increment suffix v[1-9] for exemple) if they evolve, like this it won't break experiments that use previous versions.

We can keep that in mind, but I close the issue for now. 
Do not hesitate to reopen if you think you have a worthwhile proposal.

**Comment by AudreyCLEVY** [comment]
I feel the same way, but at least we know we've got it in our heads now, and that we'll come back to it later :-)
